name: Build Xash3D Dreamcast

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-dc:
    runs-on: ubuntu-latest
    container:
      image: kazade/dreamcast-sdk:latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Fix repository ownership and sync valid submodules
      - name: Sync valid submodules
        run: |
          # Add the security exception for the container environment
          git config --global --add safe.directory /__w/xash3d-fwgs_dc/xash3d-fwgs_dc
          
          git submodule init
          git submodule deinit -f 3rdparty/dreamcast/GLdc || true
          git submodule deinit -f 3rdparty/dreamcast/kos || true
          git submodule update --init --recursive

            # 3. Clone active alternative repositories to replace the deleted links
      - name: Clone missing Dreamcast libraries
        run: |
          rm -rf 3rdparty/dreamcast/GLdc 3rdparty/dreamcast/kos
          git clone --depth 1 https://github.com/maximqaxd/GLdc.git 3rdparty/dreamcast/GLdc
          git clone --depth 1 https://github.com/maximqaxd/KallistiOS.git 3rdparty/dreamcast/kos
          
      # 4. Proceed with engine compilation
      - name: Compile Engine and SDK
        run: |
          make all

      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v4
        with:
          name: xash3d-dreamcast-build
          path: |
            build/
            *.BIN
